INSERT OR REPLACE INTO agent_profiles (id, kind, name, identifier, data, updated_at)
VALUES
  (
    'driver-003',
    'driver',
    '王强',
    '2202130',
    '{"basic":{"driver_name":"王强","driver_id":"2202130","fleet_name":"一车队","hire_date":"2018-03-16","experience_years":8},"performance_dashboard":{"summary":{"overall_score":82.6,"overall_level":"危险型","overall_trend_delta":1.6},"dimensions":{"综合排行":{"rank_position":12,"rank_total":90,"percentile":13.3,"display":"Top 13.3% (排名 12/90)","biz_note":"绩效总览"},"事故风险":{"score":86.5,"trend_delta":2.1,"trend_text":"同比+12%，环比+4%，同单位比+9%，同线路比+7%","core_risk_indicators":["闯黄灯","疲劳驾驶"],"top_indicator":"闯黄灯","alert_count":21},"能耗风险":{"score":79.2,"trend_delta":1.4,"trend_text":"同比+8%，环比+3%，同单位比+6%，同线路比+5%","core_risk_indicators":["急加速","急刹车"],"top_indicator":"急加速","alert_count":34},"服务态度":{"score":71.8,"trend_delta":0.9,"trend_text":"同比+5%，环比+2%，同单位比+4%，同线路比+3%","core_risk_indicators":["服务投诉","未礼让乘客"],"top_indicator":"服务投诉","alert_count":6},"安全评价":{"score":68.4,"trend_delta":0.6,"trend_text":"同比+3%，环比+1%，同单位比+2%，同线路比+2%","core_risk_indicators":["违规使用N档","起步未观察"],"top_indicator":"违规使用N档","alert_count":12}},"system_risk":{"level":"危险型","tags":["闯黄灯(21次)","急加速(34次)","服务投诉(6次)","违规使用N档(12次)"],"notes":"新结构 seed 数据"}},"behavior_data_analysis":{"analysis_items":[{"rank_label":"第一","dimension":"事故风险","top_indicator":"闯黄灯","alert_count":21,"insight":"第一，{事故风险}得分为{86.5}，核心风险指标为{闯黄灯}，报警{21次}，【说明路口决策激进倾向明显】。"},{"rank_label":"第二","dimension":"能耗风险","top_indicator":"急加速","alert_count":34,"insight":"第二，{能耗风险}得分为{79.2}，核心风险指标为{急加速}，报警{34次}，【说明驾驶节奏平顺性不足】。"},{"rank_label":"第三","dimension":"服务态度","top_indicator":"服务投诉","alert_count":6,"insight":"第三，{服务态度}得分为{71.8}，核心风险指标为{服务投诉}，报警{6次}，【说明服务规范执行存在波动】。"},{"rank_label":"第四","dimension":"安全评价","top_indicator":"违规使用N档","alert_count":12,"insight":"第四，{安全评价}得分为{68.4}，核心风险指标为{违规使用N档}，报警{12次}，【说明基础操作规范性仍需加强】。"}]},"interventions":{"recommendations":[{"priority":1,"indicator":"闯黄灯","action":"3日内组织路口通行规范专项培训并复盘典型事件","expected_effect":"优先降低路口高风险事件","policy_reference":"《驾驶员重点风险管理办法》第4条"},{"priority":2,"indicator":"急加速","action":"安排一周内平稳驾驶实操带教并设置线路油耗复盘","expected_effect":"降低能耗波动与急加速次数","policy_reference":"《节能驾驶专项复训指引》第2条"},{"priority":3,"indicator":"服务投诉","action":"开展服务礼仪抽查与视频回看督导","expected_effect":"稳定服务质量表现","policy_reference":"《营运服务规范》第7条"},{"priority":4,"indicator":"违规使用N档","action":"进行出车前安全操作抽测并纳入周考核","expected_effect":"压降违规操作频次","policy_reference":"《安全驾驶操作规范》第3条"}],"follow_up":{"monitor_window_days":14,"recheck_items":["闯黄灯","急加速","服务投诉","违规使用N档"]}},"appendix":{"raw_data":{"alerts_counts":{"黄灯":21,"急加速":34,"服务投诉":6,"N档":12},"ranking_snapshot":{"rank_position":12,"rank_total":90,"percentile":13.3},"source_window":{"window_days":30,"as_of":"2026-03-01"}}}}',
    '2026-03-06T09:30:00Z'
  ),
  (
    'driver-004',
    'driver',
    '赵敏',
    'D-004',
    '{"basic":{"driver_name":"赵敏","driver_id":"D-004","fleet_name":"二车队","hire_date":"2022-06-01","experience_years":3},"performance_dashboard":{"summary":{"overall_score":49.6,"overall_level":"观察型","overall_trend_delta":-0.4},"dimensions":{"综合排行":{"rank_position":38,"rank_total":90,"percentile":42.2,"display":"Top 42.2% (排名 38/90)","biz_note":"绩效总览"},"事故风险":{"score":55.4,"trend_delta":-0.3,"core_risk_indicators":["跟车过近"],"top_indicator":"跟车过近","alert_count":8},"能耗风险":{"score":51.2,"trend_delta":-0.6,"top_indicator":"急刹车","alert_count":5},"服务态度":{"score":null,"trend_delta":null,"core_risk_indicators":[],"top_indicator":"","alert_count":null},"安全评价":{"score":41.8,"trend_delta":-0.2,"trend_text":"同比—，环比-0.2%，同单位比—，同线路比—","core_risk_indicators":["起步未观察"],"top_indicator":"起步未观察","alert_count":3}},"system_risk":{"level":"观察型","tags":["跟车过近(8次)","急刹车(5次)"],"notes":"缺失值测试样例"}},"interventions":{"recommendations":[{"priority":1,"indicator":"跟车过近","action":"增加车距控制专项提醒与跟车场景复盘","expected_effect":"降低追尾隐患","policy_reference":"《安全行车行为提醒规范》第5条"},{"priority":2,"indicator":"急刹车","action":"安排站间平顺驾驶抽查","expected_effect":"压降急刹车频次","policy_reference":"《节能驾驶专项复训指引》第3条"},{"priority":3,"indicator":"起步未观察","action":"进行起步口令抽测","expected_effect":"提升起步规范性","policy_reference":"《安全驾驶操作规范》第2条"}]},"appendix":{"raw_data":{"alerts_counts":{"跟车过近":8,"急刹车":5,"起步未观察":3},"source_window":{"window_days":30,"as_of":"2026-02-28"}}}}',
    '2026-03-06T09:30:00Z'
  ),
  (
    'driver-005',
    'driver',
    '周宁',
    'D-005',
    '{"basic":{"driver_name":"周宁","driver_id":"D-005","fleet_name":"三车队","hire_date":"2017-11-08","experience_years":8},"performance_dashboard":{"summary":{"overall_score":64.3,"overall_level":"关注型","overall_trend_delta":0.8},"dimensions":{"综合排行":{"rank_position":29,"rank_total":90,"percentile":32.2,"display":"Top 32.2% (排名 29/90)","biz_note":"绩效总览"},"综合安全":{"score":64.3,"trend_delta":0.8,"biz_note":"核心考核指标"},"行车技能":{"score":72.6,"trend_delta":1.4,"biz_note":"操作平顺性下降"},"驾驶态度":{"score":59.4,"trend_delta":0.5,"biz_note":"合规意识波动"},"行为习惯":{"score":53.2,"trend_delta":0.2,"biz_note":"防御性习惯不足"}},"system_risk":{"level":"关注型","tags":["超速(9次)","急加速(11次)","投诉(2次)"],"notes":"旧结构映射样例"}},"behavior_data_analysis":{"correlation_points":[{"signal":"超速告警上升","evidence":"近30天超速9次","impact":"综合安全评分抬升"},{"signal":"急加速频繁","evidence":"近30天急加速11次","impact":"行车技能维度风险升高"}],"conclusion":"旧结构数据主要通过告警行为体现风险。"},"interventions":{"recommendations":[{"title":"超速管控复训","priority":"高","action":"重点线路限速提醒与一对一复训","rationale":"超速风险仍在上升","expected_effect":"降低超速次数"},{"title":"平顺驾驶纠偏","priority":"中","action":"急加速/急刹车专项复盘","rationale":"行车技能分抬升","expected_effect":"改善能耗与舒适性"}]},"appendix":{"raw_data":{"alerts_counts":{"speeding":9,"rapid_acceleration":11,"complaint":2},"source_window":{"window_days":30,"as_of":"2026-03-02"}}}}',
    '2026-03-06T09:30:00Z'
  ),
  (
    'driver-006',
    'driver',
    '陈波',
    '2203019',
    '{"basic":{"driver_name":"陈波","driver_id":"2203019","fleet_name":"四车队","hire_date":"2020-09-20","experience_years":5},"performance_dashboard":{"summary":{"overall_score":57.1,"overall_level":"关注型","overall_trend_delta":0.3},"dimensions":{"综合排行":{"rank_position":41,"rank_total":90,"percentile":45.6,"display":"Top 45.6% (排名 41/90)","biz_note":"绩效总览"},"事故风险":{"score":54.0,"trend_delta":0.1,"trend_text":"同比+2%，环比+1%，同单位比+1%，同线路比+1%","core_risk_indicators":["疲劳驾驶"],"top_indicator":"疲劳驾驶","alert_count":"4次"},"能耗风险":{"score":61.7,"trend_delta":0.9,"trend_text":"同比+6%，环比+3%，同单位比+4%，同线路比+2%","core_risk_indicators":["急刹车"],"top_indicator":"急刹车","alert_count":"17次"},"服务态度":{"score":48.5,"trend_delta":-0.2,"core_risk_indicators":["服务用语不规范"],"top_indicator":"服务用语不规范","alert_count":"2次"},"安全评价":{"score":52.4,"trend_delta":0.4,"core_risk_indicators":["起步未观察"],"top_indicator":"起步未观察","alert_count":"7次"}},"system_risk":{"level":"关注型","tags":["急刹车(17次)","起步未观察(7次)"],"notes":"工号查询样例"}},"behavior_data_analysis":{"analysis_items":[{"rank_label":"第一","dimension":"能耗风险","top_indicator":"急刹车","alert_count":17,"insight":"第一，{能耗风险}得分为{61.7}，核心风险指标为{急刹车}，报警{17次}，【说明驾驶平顺性仍是当前首要问题】。"},{"rank_label":"第二","dimension":"事故风险","top_indicator":"疲劳驾驶","alert_count":4,"insight":"第二，{事故风险}得分为{54.0}，核心风险指标为{疲劳驾驶}，报警{4次}，【说明夜班后半程需加强休息管理】。"},{"rank_label":"第三","dimension":"安全评价","top_indicator":"起步未观察","alert_count":7,"insight":"第三，{安全评价}得分为{52.4}，核心风险指标为{起步未观察}，报警{7次}，【说明基础操作规范仍需巩固】。"},{"rank_label":"第四","dimension":"服务态度","top_indicator":"服务用语不规范","alert_count":2,"insight":"第四，{服务态度}得分为{48.5}，核心风险指标为{服务用语不规范}，报警{2次}，【说明服务表现存在轻微波动】。"}]},"interventions":{"recommendations":[{"priority":1,"indicator":"急刹车","action":"安排平顺驾驶跟车辅导并设置周复盘","expected_effect":"降低急刹车与能耗波动","policy_reference":"《节能驾驶专项复训指引》第2条"},{"priority":2,"indicator":"疲劳驾驶","action":"优化夜班排班并加强班前状态检查","expected_effect":"压降疲劳风险","policy_reference":"《重点驾驶员健康管理办法》第6条"},{"priority":3,"indicator":"起步未观察","action":"组织起步观察动作抽测","expected_effect":"提升起步规范执行率","policy_reference":"《安全驾驶操作规范》第2条"},{"priority":4,"indicator":"服务用语不规范","action":"开展乘客沟通话术抽查","expected_effect":"稳定服务投诉率","policy_reference":"《营运服务规范》第5条"}]},"appendix":{"raw_data":{"alerts_counts":{"急刹车":17,"疲劳驾驶":4,"起步未观察":7,"服务用语不规范":2},"source_window":{"window_days":30,"as_of":"2026-03-03"}}}}',
    '2026-03-06T09:30:00Z'
  );
