INSERT OR REPLACE INTO agent_profiles (id, kind, name, identifier, data, updated_at)
VALUES
  (
    'driver-007',
    'driver',
    '张伟',
    '2204001',
    '{"basic":{"driver_name":"张伟","driver_id":"2204001","fleet_name":"五车队","hire_date":"2019-04-12","experience_years":6},"performance_dashboard":{"summary":{"overall_score":73.4,"overall_level":"关注型","overall_trend_delta":0.7},"dimensions":{"综合排行":{"rank_position":24,"rank_total":90,"percentile":26.7,"display":"Top 26.7% (排名 24/90)","biz_note":"绩效总览"},"事故风险":{"score":76.5,"trend_delta":1.2,"trend_text":"同比+7%，环比+3%，同单位比+5%，同线路比+4%","core_risk_indicators":["路口抢行"],"top_indicator":"路口抢行","alert_count":9},"能耗风险":{"score":72.8,"trend_delta":0.9,"trend_text":"同比+5%，环比+2%，同单位比+3%，同线路比+3%","core_risk_indicators":["急加速"],"top_indicator":"急加速","alert_count":13},"服务态度":{"score":69.1,"trend_delta":0.3,"trend_text":"同比+2%，环比+1%，同单位比+1%，同线路比+1%","core_risk_indicators":["报站遗漏"],"top_indicator":"报站遗漏","alert_count":4},"安全评价":{"score":65.7,"trend_delta":0.1,"trend_text":"同比+1%，环比+1%，同单位比+1%，同线路比+1%","core_risk_indicators":["起步未观察"],"top_indicator":"起步未观察","alert_count":6}},"system_risk":{"level":"关注型","tags":["路口抢行(9次)","急加速(13次)"],"notes":"同名驾驶员 seed A"}},"behavior_data_analysis":{"analysis_items":[{"rank_label":"第一","dimension":"事故风险","top_indicator":"路口抢行","alert_count":9,"insight":"第一，{事故风险}得分为{76.5}，核心风险指标为{路口抢行}，报警{9次}，【说明路口通行稳定性需重点关注】。"},{"rank_label":"第二","dimension":"能耗风险","top_indicator":"急加速","alert_count":13,"insight":"第二，{能耗风险}得分为{72.8}，核心风险指标为{急加速}，报警{13次}，【说明平顺驾驶表现仍有波动】。"},{"rank_label":"第三","dimension":"服务态度","top_indicator":"报站遗漏","alert_count":4,"insight":"第三，{服务态度}得分为{69.1}，核心风险指标为{报站遗漏}，报警{4次}，【说明服务流程执行需要加强】。"},{"rank_label":"第四","dimension":"安全评价","top_indicator":"起步未观察","alert_count":6,"insight":"第四，{安全评价}得分为{65.7}，核心风险指标为{起步未观察}，报警{6次}，【说明基础操作规范性仍需提升】。"}]},"interventions":{"recommendations":[{"priority":1,"indicator":"路口抢行","action":"组织路口通行规范复训并跟车抽查","expected_effect":"降低路口高风险事件","policy_reference":"《驾驶员重点风险管理办法》第4条"},{"priority":2,"indicator":"急加速","action":"开展平顺驾驶专项复训和油耗复盘","expected_effect":"降低急加速频次与能耗波动","policy_reference":"《节能驾驶专项复训指引》第2条"},{"priority":3,"indicator":"报站遗漏","action":"安排服务流程抽查与语音播报复盘","expected_effect":"稳定营运服务执行质量","policy_reference":"《营运服务规范》第5条"},{"priority":4,"indicator":"起步未观察","action":"进行起步前观察动作抽测","expected_effect":"提升基础操作规范执行率","policy_reference":"《安全驾驶操作规范》第2条"}]},"appendix":{"raw_data":{"alerts_counts":{"路口抢行":9,"急加速":13,"报站遗漏":4,"起步未观察":6},"source_window":{"window_days":30,"as_of":"2026-03-04"}}}}',
    '2026-03-07T00:10:00Z'
  ),
  (
    'driver-008',
    'driver',
    '张伟',
    '2204002',
    '{"basic":{"driver_name":"张伟","driver_id":"2204002","fleet_name":"六车队","hire_date":"2021-08-18","experience_years":4},"performance_dashboard":{"summary":{"overall_score":58.9,"overall_level":"观察型","overall_trend_delta":-0.2},"dimensions":{"综合排行":{"rank_position":43,"rank_total":90,"percentile":47.8,"display":"Top 47.8% (排名 43/90)","biz_note":"绩效总览"},"事故风险":{"score":60.2,"trend_delta":0.2,"trend_text":"同比+3%，环比+1%，同单位比+2%，同线路比+1%","core_risk_indicators":["跟车过近"],"top_indicator":"跟车过近","alert_count":7},"能耗风险":{"score":57.5,"trend_delta":-0.1,"trend_text":"同比+1%，环比—，同单位比+1%，同线路比—","core_risk_indicators":["急刹车"],"top_indicator":"急刹车","alert_count":8},"服务态度":{"score":55.4,"trend_delta":-0.3,"trend_text":"同比—，环比-1%，同单位比—，同线路比—","core_risk_indicators":["服务投诉"],"top_indicator":"服务投诉","alert_count":2},"安全评价":{"score":52.1,"trend_delta":-0.4,"trend_text":"同比—，环比-1%，同单位比—，同线路比—","core_risk_indicators":["违规使用N档"],"top_indicator":"违规使用N档","alert_count":3}},"system_risk":{"level":"观察型","tags":["跟车过近(7次)","急刹车(8次)"],"notes":"同名驾驶员 seed B"}},"behavior_data_analysis":{"analysis_items":[{"rank_label":"第一","dimension":"事故风险","top_indicator":"跟车过近","alert_count":7,"insight":"第一，{事故风险}得分为{60.2}，核心风险指标为{跟车过近}，报警{7次}，【说明跟车距离控制仍需加强】。"},{"rank_label":"第二","dimension":"能耗风险","top_indicator":"急刹车","alert_count":8,"insight":"第二，{能耗风险}得分为{57.5}，核心风险指标为{急刹车}，报警{8次}，【说明平顺驾驶稳定性不足】。"},{"rank_label":"第三","dimension":"服务态度","top_indicator":"服务投诉","alert_count":2,"insight":"第三，{服务态度}得分为{55.4}，核心风险指标为{服务投诉}，报警{2次}，【说明服务过程需加强复盘】。"},{"rank_label":"第四","dimension":"安全评价","top_indicator":"违规使用N档","alert_count":3,"insight":"第四，{安全评价}得分为{52.1}，核心风险指标为{违规使用N档}，报警{3次}，【说明基础操作规范仍需持续督导】。"}]},"interventions":{"recommendations":[{"priority":1,"indicator":"跟车过近","action":"增加车距控制提醒并开展跟车场景复盘","expected_effect":"降低追尾隐患","policy_reference":"《安全行车行为提醒规范》第5条"},{"priority":2,"indicator":"急刹车","action":"安排站间平顺驾驶抽查","expected_effect":"压降急刹车频次","policy_reference":"《节能驾驶专项复训指引》第3条"},{"priority":3,"indicator":"服务投诉","action":"开展服务礼仪回看与话术复训","expected_effect":"稳定乘客服务质量","policy_reference":"《营运服务规范》第7条"},{"priority":4,"indicator":"违规使用N档","action":"组织出车前操作抽测","expected_effect":"压降违规操作频次","policy_reference":"《安全驾驶操作规范》第3条"}]},"appendix":{"raw_data":{"alerts_counts":{"跟车过近":7,"急刹车":8,"服务投诉":2,"违规使用N档":3},"source_window":{"window_days":30,"as_of":"2026-03-04"}}}}',
    '2026-03-07T00:10:00Z'
  );
